#!/bin/bash
#
# Copyright (C) 2006 Holger Macht <holger@homac.de>
#
# Author: Holger Macht <holger@homac.de>
#
# This file is released under the GPLv2.
#

SYS_PATH=/sys/devices/platform

if [ "$1" = "dock" ]; then
    echo "docking should have been done automatically by the dock driver..."

elif [ "$1" = "undock" ]; then
    for I in $SYS_PATH/dock*; do
	DOCKED=`cat $I/docked`
	if [ "$DOCKED" = "1" ]; then
	    echo undocking $I
	    echo -n 1 > $I/undock
	fi
    done
fi
