#!/bin/bash
# dock/undock script for Thinkpad X61

export DISPLAY=:0

if [ "$1" = "dock" ]; then
        echo "X200 dock"
        # set external display resolution & dpi
	xrandr --output LVDS1 --off
	xrandr --output DP3 --off --output DP2 --off --output DP1 --off --output HDMI2 --mode 1680x1050 --pos 1680x0 --rotate normal --output HDMI1 --off --output LVDS1 --off --output VGA1 --mode 1680x1050 --pos 0x0 --rotate normal
elif [ "$1" = "undock" ]; then
        echo "X200 undock"
        
	# turn external display off, internal on and set res
	xrandr --output HDMI2 --off
	xrandr --output DP3 --off --output DP2 --off --output DP1 --off --output HDMI2 --off --output HDMI1 --off --output LVDS1 --mode 1280x800 --pos 0x0 --rotate normal --output VGA1 --off
fi
